osx_image: xcode8
language: objective-c
script: set -o pipefail && xcodebuild test -project Dwifft.xcodeproj -scheme Dwifft -sdk iphonesimulator10.0 -destination 'platform=iOS Simulator,name=iPhone 7' | xcpretty -c
